# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Jotaro"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://example.com/"
tags = ["tags","categories"]
features = []
min_version = "0.31"

[author]
  name = "Jotaro Shigeyama"
  homepage = "jotaros.github.io"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
[params]
  customCSS = ["css/custom.css"]